# Generated by Django 5.1 on 2024-08-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khomafy_app', '0003_alter_song_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
