# Generated by Django 5.1 on 2024-08-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khomafy_app', '0004_song_song_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('artist', models.CharField(max_length=200)),
                ('songs', models.ManyToManyField(blank=True, related_name='playlists', to='khomafy_app.song')),
            ],
        ),
    ]
