# Generated by Django 5.1 on 2024-08-08 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khomafy_app', '0005_playlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='artist',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='title',
        ),
    ]
